### ISSUE TITLE
Blinking of old content

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#169]
Try this: 
1. Run Launcher + Products
2. Go to Products by clicking in the left menu.
   - You will see the list of products
3. Go to "Edit a product" page
   - You will see the product details
4. Click on Launcher "Home" button
5. Go to Products by clicking in the left menu
   - For a frame, you will see the product details and then you will see the list of products

Reproducible at http://alby-424.mysampleapp.com/products

Screengrab:

![bug](https://cloud.githubusercontent.com/assets/566463/11438406/ef0f9d70-94f4-11e5-85df-a03f93ea7c1f.gif)

**Comment by tomalec** [comment]
Probably it's because our visual, local routing is faster than async fetching and updating JSON view model via WebSocket

**Comment by tomalec** [comment]
Maybe we should push the RedirectURL to puppet-redirect from server after the new page/partial comes not before

**Comment by warpech** [comment]
The URL is changed when you click on `<a href="">...</a>`. RedirectURL is not involved.

From my understanding, it is because `juicy-display-router` switches the workspace at the time when the URL changes, not when the actual response is received.

**Comment by tomalec** [comment]
I have managed to remove the Flash Of Undesired Content which was shown between the moment when `juicy-display-router` shows the workspace (due to `window.location` change), and the moment when response with new JSON and comes.

Now Launcher simply returns visible URI as a art of view-model, and `<launcher-display-router>`uses it to change the workspaces.


However, there is still (shorter) FOUC. Probably due to Polymer's `dom-bind`ing & `imported-template` latency

**Comment by tomalec** [comment]
I'm afraid that due to asynchronous nature of imported-template, and unknown deep structure of nested sub partials, it may be hard to figure out arbitrary timing to finally change the display.

I would say, we need to re-think entire SPWorkspaces navigation flow.

Some, blood fresh spec proposal to consider: http://chrislord.net/index.php/2015/04/24/web-navigation-transitions/
https://docs.google.com/document/d/17jg1RRL3RI969cLwbKBIcoGDsPwqaEdBxafGNYGwiY4/edit#heading=h.pcll678prpwu

**Comment by tomalec** [comment]
Another catch is that we may notice a blink due to precalculate in juicy tile list, as before refresh, and repack, `-list` resets all ShadowDOM styles to get somewhat intrinsic dimension

**Comment by warpech** [comment]
On Friday's meeting it was discussed that default settings will be width 100%, height `unknown` (interpreted as 1px, grow with content). Without `precalculate`.

When the layout editor is opened for the first time, layout editor will automatically apply `calculate` to all height `unknown`.

**Comment by tomalec** [comment]
`precalculate*` issue is tracked at https://github.com/StarcounterSamples/Launcher/issues/191

**Comment by tomalec** [comment]
Yet another chromium issue that causes blinking, and requires ugly workarounds https://code.google.com/p/chromium/issues/detail?id=581176

**Comment by warpech** [comment]
Closing as fixed with other fixes.
