### ISSUE TITLE
Layout editor should not allow editing of pages which do not have PartialId

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#207]
Testing current master branches of Launcher and KitchenSink, it is possible to edit layouts of KitchenSink subpages (such as TextPage, etc), but it is not possible to save the changes. 

This is because PartialId is `undefined`, since these pages are not loaded through `Self.GET` (see https://github.com/StarcounterSamples/KitchenSink/issues/23).

@miyconst, @tomalec can we disable editing of not saveable layouts?

**Comment by miyconst** [comment]
I can filter out the `juicy-tile-list` without `juicy-tiles-setup-sync`. How else can I check whether a list is savable?

**Comment by tomalec** [comment]
I think we should implement it in `juicy-tile-setup-sync` or `launcher-include`, as this is the element meant to coverall client-server communication problem for layouts

For example `-setup-sync`, or `launcher-include` will mark such juicy-tile-grid as 
- `disabled` if we would like to disable juicy-tile-grid features as well
- `editing-disabled` if we would like to disable editing only

**Comment by warpech** [comment]
Alternatively, maybe `<starcounter-include>` should remove `juicy-tile-list` and `juicy-tiles-setup-sync` from DOM if there is no PartialId?

Related: https://github.com/StarcounterPrefabs/launcher-include/issues/10

**Comment by miyconst** [comment]
>Alternatively, maybe `<starcounter-include>` should remove `juicy-tile-list` and `juicy-tiles-setup-sync` from DOM if there is no PartialId?

I like this idea.

**Comment by tomalec** [comment]
I don't ;)
As, then we will need to modify light dom structure and move elements one
level above according tomodel attached. What will make it quite
inconsistent. Will require us to do everything on attached rather than on
created. Plus it will give an opportunity to an app to opt out from
Launchers layout in non documented, hard to explain way.

I would rather suggest that ´starcounter-include´ will disable setup sync
if there is no partial id.
23 mar 2016 19:48 "Konstantin" <notifications@github.com> napisał(a):

**Comment by miyconst** [comment]
I just want to let people use our Launcher without using the editor.

This is the case for SweOffshore. They want the launcher, do not want the editor with `juicy-tile-table`. And `juicy-tile-table` sets its `min-width` to the current available width by default, also adds some more client side files, code, etc.

**Comment by tomalec** [comment]
Do they wat to disable juicy tiles for all partials or only theirs?
25 mar 2016 14:21 "Konstantin" <notifications@github.com> napisał(a):

**Comment by miyconst** [comment]
All the partials. And I told Jens to just remove `launcher-include`, it works for now.

**Comment by warpech** [comment]
> As, then we will need to modify light dom structure and move elements one
level above according tomodel attached.

Why move elements? It is not moving, only attaching and detaching:

```html
<template id="partial-template">
    <template if="{{hasLayout}}">
        <juicy-tiles-setup-sync api-url="/sc/layout"></juicy-tiles-setup-sync>
        <juicy-tile-table defaultTileSetup='{
                "height": 1,
                "heightDynamic": true,
                "width": "100%",
                "widthFlexible": true
            }' refreshonmutation>
            <template is="imported-template"></template>
        </juicy-tile-table>
    </template>
    <template if="{{!hasLayout}}">
        <template is="imported-template"></template>
    </template>
</template>
```

**Comment by warpech** [comment]
> This is the case for SweOffshore. They want the launcher, do not want the editor with juicy-tile-table. And juicy-tile-table sets its min-width to the current available width by default, also adds some more client side files, code, etc.

Please clarify: do they want to disable the editor, or to disable `juicy-tile-table`?

> I told Jens to just remove launcher-include, it works for now.

`juicy-tile-table` with synchronised layouts is the only functionality that "Launcher's starcounter-include" provides over the regular "starcounter-include". If someone does not like `j-t-t`, then your solution is *the* solution, not a workaround.

What I am proposing here is that "Launcher's starcounter-include" should work like regular "starcounter-include" if the page is not loaded using Self.GET.

**Comment by tomalec** [comment]
> Why move elements?

as you wrote
```
<template id="partial-template">
    <template if="{{hasLayout}}">
        <juicy-tile-table>
            <template is="imported-template"></template>
        </juicy-tile-table>
    </template>
    <template if="{{!hasLayout}}">
        <template is="imported-template"></template>
    </template>
</template>
```
If `hasLayout` it will be wrapped in `<juicy-tile-table>` if `!hasLayout` it will not. We stamp that in light DOM, so it will move elements from and in `j-t-t`.

What is more, your example requires Polymer's `dom-bind` inside and `dom-if` I really doubt if it's a good idea to add it there due to performance, debugging, workflow, and binding problems.

>  I like using DOM as our API, not adding additional notion of "disabled" `juicy-tile-table`.

I like it too, and `juicy-tile-table` already has the concept of being `disabled`. Many other elements has it: `input`, `button`, `select`.

> Please clarify: do they want to disable the editor, or to disable juicy-tile-table?

I think it's a key question here.

> If someone does not like j-t-t, then your solution is the solution, not a workaround.

Totally agree.


>  What I am proposing here is that "Launcher's starcounter-include" should work like regular "starcounter-include" if the page is not loaded using Self.GET.

Why? - I'm not sure if that is what we need. Some time ago I proposed many ways to achieve that, to opt out from (then) Launcher-partial, and use starcounter-partial, or just imported-template. But, we all agreed that we want to force `juicy-tiles` for all partials. Then if a developer would like to make sure that nobody will mess with his/her content, he/she may always use imported-template and nested view-model instead of `X.GET`

**Comment by warpech** [comment]
Closing, because it is related to the old layout editor which was phased out.
