### ISSUE TITLE
Do not determine the current workspace based on the URL

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#208]
Extracted from https://github.com/Starcounter/Starcounter/issues/2902

Currently, Launcher determines the current workspace by comparing the first segment of the URL with workspace AppNames.

The code for that is here: https://github.com/StarcounterPrefabs/Launcher/blob/aca346a398529e79562fae01c6a2dfe108f359f9/src/Launcher/wwwroot/Launcher/viewmodels/LauncherTemplate.html#L110-L113

This is wrong, because it stops working if the app does not follow the naming principle that the first segment needs to match AppName. It makes it unneccesarily hard for the beginners (like this one: https://github.com/Starcounter/InvoiceDemo/issues/55). We should still have this rule, but do not fail if it is not satisfied.

The matching mechanism should be changed by adding a `CurrentWorkspace` property to Launcher's viewmodel and matching against it. It can be a string value (matching `AppName`) or a number value (an index in the `workspace`s array).

**Comment by warpech** [comment]
I pushed a potential fix but have a problem with it. @chrhol could you please take a look? A boolean change made in `WrapInLauncher` is not delivered to the client. Maybe this is some obvious mistake by me, but I cannot find it.

I set `ActiveWorkspace` to `true` on the server:

![2016-03-24 10_59_47-launcher - microsoft visual studio](https://cloud.githubusercontent.com/assets/566463/14013966/cec549b2-f1af-11e5-8c15-c7640ac11656.png)

But it is still delivered to the client as `false`:

<img width="1110" alt="screen shot 2016-03-24 at 11 00 17" src="https://cloud.githubusercontent.com/assets/566463/14013965/ca073d68-f1af-11e5-8225-a35b924f6ed2.png">

**Comment by chrhol** [comment]
The problems comes from how the merger works. In some cases there can be more than one Json coming from the launcher (and actually containing the same values). So the property `ActiveWorkspaces` is correctly set to `true` in the first sibling but not updated in the second and the value will be overwritten when it comes to the client.

As a workaround I added so that `ActiveWorkspace` is set on all silbings of the same type (added in the merge callback). We'll have to investigate on how we can solve this properly later and avoid having multiple responses added.

**Comment by warpech** [comment]
Great, thanks! Is there any issue that should be created in Starcounter for this? I want to close this issue once I merge the solution to `master`.

**Comment by warpech** [comment]
Done, closing
