### ISSUE TITLE
Lanucher with Kitchensink return error "Cannot read property 'hasAttribute' of undefined"

### ISSUE THREAD

**Issue by aloscha** [StarcounterPrefabs/Launcher#213]
After run Launcher with Kitchensink, please do steps:
1. Start Kitchensink with KitchenSink/Text
2. Go to Password tab, by clicking in menu
3. Go to Textarea tab, by clicking in menu

Now we have error
`polymer-mini.html:2061 Uncaught TypeError: Cannot read property 'hasAttribute' of undefined`

Now current page is frozen and we can't change it.

**Comment by warpech** [comment]
Reproducible for me with Chrome. @miyconst could you please take a look?

**Comment by warpech** [comment]
This does not happen with KitchenSink standalone.

**Comment by miyconst** [comment]
For some reason resetting setup of a `juicy-tile-table` causes this error. This happens when a new partial loaded and setup set to `null` to refresh it.

The issue happens [here](https://github.com/Juicy/juicy-tile-list/blob/gh-pages/src/juicy-tile-list.html#L401): 

```js
if(tile.element.hasAttribute('juicy-style')){
```

The `tile.element` is undefined.

@tomalec could you take a look please?

---

@aloscha provide some more info when you report an issue please. The exception stack trace is always useful.

**Comment by tomalec** [comment]
I have add a fix to `juicy-tile-list` it's not perfect, and I didn't add tests, but once I will finish `<juicy-composer>` the scenario would be completely different, and this functionality & code will be moved there.
