### ISSUE TITLE
Invalid Workspace behavior with SignIn app

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/Launcher#224]
Steps to reproduce:

1. Start Launcher and SignIn.
2. Navigate to `http://localhost:8080/signin/signinuser`.
3. Click on the `Registration` button.
4. The registration form should appear.
5. Click on the `Sign in` button.
6. **The page url changes, but the html remains.**
7. Click on the `Sign in` button again.
8. **The html changes, but Launcher creates another Workspace for SignIn app.**

cc @warpech, @chrhol

**Comment by warpech** [comment]
Thanks! Taking this on me for investigation

**Comment by warpech** [comment]
Problem appears at point (3) of the above reproduction steps, because a new workspace is created after clicking on the "Registration" button. 

Expected is for Launcher to reuse the existing workspace from the SignIn app.

**Comment by warpech** [comment]
Actually the problem appears at point (1), because the initial response contains `AppName: "Launcher"`.

The expected value is `AppName: "SignIn"`

<img width="1434" alt="screen shot 2016-04-11 at 18 25 14" src="https://cloud.githubusercontent.com/assets/566463/14434384/c750802c-0012-11e6-8d8f-137f94801a09.png">

**Comment by warpech** [comment]
I have perhaps the complete C# half of the fix (see the above commit).

Now additional workspaces are not created and the "Registration" button consistently does **not** work (step 7-8 work the same as step 5-6).

Tomorrow, among other tasks, I will further investigate the client side part of the solution. It might be related to https://github.com/StarcounterPrefabs/Launcher/issues/181.

Client side switching to the "Registration" form fails consistently in `starcounter-include` and Launcher's `starcounter-include`.

**Comment by warpech** [comment]
The problem is really similar to #181 - the `Html` property in `partial` does not get notified by Polymer, unless the whole partial is replaced. 

This can only be implemented by one of the below:
1. converting Launcher's `starcounter-include` and `starcounter-include` to Polymer elements
2. waiting until Polymer implements https://github.com/Polymer/polymer/issues/1796 / https://github.com/Polymer/polymer/pull/3460 and making Launcher's `starcounter-include` and `starcounter-include` aware of Polymer's subscription API.

**Comment by warpech** [comment]
Or maybe actually there is a 3rd way... Hang on!

**Comment by warpech** [comment]
The reason why point (6) fails is that this `workspaces[0].Launcher.MergedHtml` is updated, but `workspaces[0].Html` is not. I will investigate more.

**Comment by warpech** [comment]
@chrhol this is where I need your help. Could you please investigate?

**Comment by warpech** [comment]
Why there is also a red rectangle around the value of `PartialId`? That's another good question. This value changes correctly when loading `SignInFormPage` and switching to `RegistrationFormPage`. But it does not change when loading `RegistrationFormPage` and switching to `SignInFormPage`.

**Comment by miyconst** [comment]
@warpech I investigated patches coming from server, the was a patch for `MergedHtml`, but no patch for `Html` property, so it was not notification issue.

Maybe you already solved it, just to note.

**Comment by warpech** [comment]
> @warpech I investigated patches coming from server, the was a patch for MergedHtml, but no patch for Html property, so it was not notification issue.

Both `starcounter-include` and Launcher's `starcounter-include` are reading at `Html` property. No client-side code is actually using `MergedHtml`.

**Comment by miyconst** [comment]
But the `Html` property should be updated from server side, right? If there is no patch for the property, no updates.

**Comment by warpech** [comment]
Yes, this is why I ask @chrhol to investigate this.

**Comment by miyconst** [comment]
@warpech your workaround seems to work, do you think we can merge it together with https://github.com/StarcounterPrefabs/Launcher/issues/181 to master?

**Comment by warpech** [comment]
`master` branch updated with work in progress of changes to Launcher's `starcounter-include`. The client-side workaround bypasses the problem described in #224.

This issue is still not solved, because server does not always send patches about changed `Html` and `Launcher.PartialId` (see https://github.com/StarcounterPrefabs/Launcher/issues/224#issuecomment-208798948 and https://github.com/StarcounterPrefabs/Launcher/issues/224#issuecomment-208806003).

**Comment by chrhol** [comment]
> @warpech I investigated patches coming from server, the was a patch for MergedHtml, but no patch for Html property, so it was not notification issue.

This is the problem. The `Html` property is currently added as a hack in the serializer when sending all siblings. So there is no property to send a patch for when parts of the merged html changes. 

My other change, that we only update the changed parts for siblings as well, instead of sending everything every time, had this unfortunate consequence.

We really need to sit down and see how we can solve the htmlmerger properly. This will also be needed to finalize the work @per-samuelsson have done to change the behaviour of Page/Partial pattern.

> Actually the problem appears at point (1), because the initial response contains AppName: "Launcher".

I found a place in the merger when the callback is invoked that used the wrong AppName, but after I fixed this, the issue above gets even more obvious. After the fix going to the Registration-page doesn't work either. 

The fix in the merger is not pushed.

**Comment by malx122** [comment]
This issue is creating a lot of problem for us right now. Not only with SignIn, but with a lot of apps. It's so severe that I would actually give it highest priority!

**Comment by chrhol** [comment]
> This issue is creating a lot of problem for us right now. Not only with SignIn, but with a lot of apps. It's so severe that I would actually give it highest priority!

Have you tried the workaround from @warpech? I will submit the fix with incorrect AppName and that will solve the PartialId problem. With these two things in place it seem to work again.

**Comment by warpech** [comment]
With today fixes made by me (released in Launcher 4.0.1) and made by @chrhol (released as next nightly after 2.1.1742) the problem is not reproducible anymore.

@chrhol since the problem still remains in `htmlmerger` (which affects apps when Launcher is **not** running), could you please open an issue about that? And then close this one.

I have opened an issue about possibility of removing `htmlmerger` (https://github.com/Starcounter/Starcounter/issues/3495)

**Comment by ubbeK** [comment]
Just tested the Registration - SignIn bug while testing [SignIn Issue 22](https://github.com/StarcounterSamples/SignIn/issues/22) and it has been fixed with the nightly build 2.1.176

**Comment by miyconst** [comment]
I confirm the fix.

@warpech, @chrhol - thank you for fixing.
@ubbeK - thank you for testing.

Closing the issue.
