### ISSUE TITLE
Element tree and element identifiers

### ISSUE THREAD

**Issue by Starcounter-Jack** [StarcounterPrefabs/Launcher#57]
## Element identifiers

Each element (HTML element or container) should have a friendly name as a identifier. The purpose is to make it simpler to navigate the tree. The identifier should be editable by the user. 
## Default identifier

Let's implement an ID generator that generates a pleasant default name of each element. The ID should be unique within its template. One idea to generate an ID is using the element name (the the element represents a container the word `Group` could be used) followed by a dash and:
1. The first label, or;
2. The first content text, or;
3. A sequential number within the template

```
Group-1
   Button-Save
   Button-Ok
   Input-FirstName
Group-2
   Button-3
   Button-4
```

**Comment by tomalec** [comment]
Since https://github.com/Polyjuice/Launcher/commit/cc33c1ce724e0704c1bce64cc618e3a6cf21f762  we  are able to identify nodes like : `AppNameSpace/index` so currently we do use it as a fallback identifier if we fail to read something from the content.

In general since https://github.com/Juicy/juicy-tile-list/commit/34c8964e9b1a3898002ef0486fbe498d0e999039 tiles (those in Shadow DOM) does have id attribute and elements in Light DOM corresponding `juicytile` attribute equal to this id. So, from browser validation perspective, it needs to be unique only withing single juicy-tile-list (layoutable partial).

We are also ready to provide a feature to set custom names/labels for elements, we only need to figure out how to handle it on server-side (store/compose/attach per what - html, url, set).

**Comment by tomalec** [comment]
Custom name can now be set for any item: individual tile, group, entire juicy-tile-list.

@warpech, do we need better suggested/display by default names?

**Comment by warpech** [comment]
It would be nice to have default display names better than `AppName/index`, but what we have now is sufficient for the time being.

Detecting display name is related to detecting the type of content for the purpose of the tree element icon as proposed by me here: https://github.com/Polyjuice/Polyjuice/issues/44

Current priority: low.

**Comment by tomalec** [comment]
AppName/index is default id, display name should stay as before: name guessed from the content

**Comment by warpech** [comment]
Fair enough. Please note that this ticket is *only* about display names, not about internally used element id.

**Comment by warpech** [comment]
Closing, because it is related to the old layout editor which was phased out.

With the new blending, slot names are the element identifiers.
